In [2]:
pip install pandas

Requirement already satisfied: pandas in .\env\lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in .\env\lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in .\env\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\env\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in .\env\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd
import numpy as np
a = np.arange(1,21)
b = pd.Series(a)
print(a)
print("- --------------")
print(b)
print(type(b))
print(pd.DataFrame(a))
c = pd.DataFrame({'x':a, 'y':a, 'z':a})
c

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
- --------------
0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
12    13
13    14
14    15
15    16
16    17
17    18
18    19
19    20
dtype: int64
<class 'pandas.Series'>
     0
0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
9   10
10  11
11  12
12  13
13  14
14  15
15  16
16  17
17  18
18  19
19  20

     x   y   z
0    1   1   1
1    2   2   2
2    3   3   3
3    4   4   4
4    5   5   5
5    6   6   6
6    7   7   7
7    8   8   8
8    9   9   9
9   10  10  10
10  11  11  11
11  12  12  12
12  13  13  13
13  14  14  14
14  15  15  15
15  16  16  16
16  17  17  17
17  18  18  18
18  19  19  19
19  20  20  20

In [4]:
df = pd.read_csv('data-.csv')
print(df)
print("----------------------------------------")
print(df.head(1))
print("----------------------------------------")
print(df.head(2))
print("----------------------------------------")
print(df.tail(1))
print("----------------------------------------")
print(df.info())
print("----------------------------------------")
print(df.describe())

    name  age     city category  sales  a   b
0   John   25    Delhi        A    200  5  10
1   Riya   22   Mumbai        B    120  2   3
2   Aman   30     Pune        A    250  7   8
3   Neha   27  Kolkata        C    300  4   6
4  Arjun   35   Jaipur        B    200  1   9
----------------------------------------
   name  age   city category  sales  a   b
0  John   25  Delhi        A    200  5  10
----------------------------------------
   name  age    city category  sales  a   b
0  John   25   Delhi        A    200  5  10
1  Riya   22  Mumbai        B    120  2   3
----------------------------------------
    name  age    city category  sales  a  b
4  Arjun   35  Jaipur        B    200  1  9
----------------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      5 non-null      str
 1   age       5 non-null      int64
 2   city      5 non-null      str
 3   category  5 non-null      str
 4   sales     5 non-null      int64
 5   a         5 non-null      int64
 6   b         5 non-null      int64
dtypes: int64(4), str(3)
memory usage: 412.0 bytes
None
----------------------------------------
             age       sales         a          b
count   5.000000    5.000000  5.000000   5.000000
mean   27.800000  214.000000  3.800000   7.200000
std     4.969909   66.932802  2.387467   2.774887
min    22.000000  120.000000  1.000000   3.000000
25%    25.000000  200.000000  2.000000   6.000000
50%    27.000000  200.000000  4.000000   8.000000
75%    30.000000  250.000000  5.000000   9.000000
max    35.000000  300.000000  7.000000  10.000000

In [5]:
import pandas as pd
arr = [10,20,30,40,50]
arr1 = pd.Series(arr)
print(arr1)

0    10
1    20
2    30
3    40
4    50
dtype: int64

## **Series Attribute**

In [6]:
arr1.size

5

In [7]:
arr1.shape

(5,)

In [8]:
arr1.name

In [9]:
arr1.is_unique

True

In [10]:
arr1.index

RangeIndex(start=0, stop=5, step=1)

In [11]:
arr1.values

array([10, 20, 30, 40, 50])

## Series Methods and Method Chaining

In [12]:
arr1.tail(1)

4    50
dtype: int64

In [13]:

arr1.head(1)

0    10
dtype: int64

In [14]:
import numpy as np
a = np.arange(100,1000)
s = pd.Series(a)
# s
# s.sample(10)
# s.value_counts
# s.sort_values(ascending=False)
# s.sort_index()
s.head(100).sample(10).tail(5).sort_values(ascending=False).sort_index()

5     105
9     109
59    159
70    170
97    197
dtype: int64

## Mathematical Functions

In [15]:
arr = np.array([1,7,3,11,4,6,8,np.nan,np.nan,np.nan])
a = pd.Series(arr)
a

0     1.0
1     7.0
2     3.0
3    11.0
4     4.0
5     6.0
6     8.0
7     NaN
8     NaN
9     NaN
dtype: float64

In [16]:
m = a.size
m

10

In [17]:
m= a.count()
m

np.int64(7)

In [18]:
a.sum()

np.float64(40.0)

In [19]:
a.product()

np.float64(44352.0)

In [20]:
a.mean()

np.float64(5.714285714285714)

In [21]:
a.mode()

0     1.0
1     3.0
2     4.0
3     6.0
4     7.0
5     8.0
6    11.0
dtype: float64

In [22]:
a.std()

np.float64(3.3523268393901033)

In [23]:
a.var()

np.float64(11.238095238095239)

In [24]:
a.min()

np.float64(1.0)

In [25]:
a.max()

np.float64(11.0)

In [26]:
a.describe()

count     7.000000
mean      5.714286
std       3.352327
min       1.000000
25%       3.500000
50%       6.000000
75%       7.500000
max      11.000000
dtype: float64

## Indexing and Slicing

In [27]:
a.iloc[1]

np.float64(7.0)

In [28]:

import pandas as pd
a= pd.Series([10,20,30,40,50],index=['a','b','d','e','n'])
a

a    10
b    20
d    30
e    40
n    50
dtype: int64

In [29]:
a.loc['a']

np.int64(10)

In [30]:
a.iloc[1:5]

b    20
d    30
e    40
n    50
dtype: int64

## Editing  a Series

a[1:5]

In [31]:
a= pd.Series([10,20,30,40,50],index=['a','b','d','e','n'])
# a[1:5]
# a[0]=100
# a
a ['a':'d']= [200,300,400]
a ['a':'d']= 25
a

a    25
b    25
d    25
e    40
n    50
dtype: int64

## *Null Value HAndling*

In [32]:
arr = np.array([1,7,3,11,4,6,8,np.nan,np.nan,np.nan])
a = pd.Series(arr)
a.isnull()
a.isnull().sum()

np.int64(3)

In [33]:
a.notnull()

0     True
1     True
2     True
3     True
4     True
5     True
6     True
7    False
8    False
9    False
dtype: bool

In [34]:
a.hasnans

True

## Unique Values

In [35]:
arr = np.array([1,7,3,7,3,11,4,6,8,np.nan,np.nan,np.nan])
a = pd.Series(arr)
a

0      1.0
1      7.0
2      3.0
3      7.0
4      3.0
5     11.0
6      4.0
7      6.0
8      8.0
9      NaN
10     NaN
11     NaN
dtype: float64

In [36]:
a.unique()

array([ 1.,  7.,  3., 11.,  4.,  6.,  8., nan])

In [37]:
a.nunique()

7

In [38]:
a.is_unique

False

In [39]:
sorted(a)

[1.0, 3.0, 3.0, 4.0, 6.0, 7.0, 7.0, 8.0, 11.0, nan, nan, nan]

## Python in-built function

## Type Conversion

In [40]:
series = np.array([1,2,4,7,3,8])
s = pd.Series(series)
s.astype(int)
s

0    1
1    2
2    4
3    7
4    3
5    8
dtype: int64

In [41]:
s.astype(float)
s

0    1
1    2
2    4
3    7
4    3
5    8
dtype: int64

In [42]:
s.astype(bool)
s

0    1
1    2
2    4
3    7
4    3
5    8
dtype: int64

In [43]:
s.__len__

<bound method Series.__len__ of 0    1
1    2
2    4
3    7
4    3
5    8
dtype: int64>

## Membership Operator

In [44]:
series = np.array([14,21,40,76,31,18])
s = pd.Series(series)
s

0    14
1    21
2    40
3    76
4    31
5    18
dtype: int64

In [45]:
s.isin

<bound method Series.isin of 0    14
1    21
2    40
3    76
4    31
5    18
dtype: int64>

In [46]:
print(0 in s)

True

In [47]:
print(s.isin([10,40,21]))

0    False
1     True
2     True
3    False
4    False
5    False
dtype: bool

# Looping over a series

In [48]:
for i in s:
    print(i)

14
21
40
76
31
18

In [49]:
for i,v in s.items():
    print(i,v)

0 14
1 21
2 40
3 76
4 31
5 18

In [50]:
def square(x):
    return x*x
print(s.apply(square))

0     196
1     441
2    1600
3    5776
4     961
5     324
dtype: int64

## Arthematic operators

In [51]:
s+5

0    19
1    26
2    45
3    81
4    36
5    23
dtype: int64

In [52]:
s*5

0     70
1    105
2    200
3    380
4    155
5     90
dtype: int64

In [53]:
s/5

0     2.8
1     4.2
2     8.0
3    15.2
4     6.2
5     3.6
dtype: float64

In [54]:
s-5

0     9
1    16
2    35
3    71
4    26
5    13
dtype: int64

In [55]:
s%5

0    4
1    1
2    0
3    1
4    1
5    3
dtype: int64

In [56]:
s//5

0     2
1     4
2     8
3    15
4     6
5     3
dtype: int64

In [57]:
arr1 = np.array([22,44,55,77,88])
s1 = pd.Series(arr1)
arr2 = np.array([11,34,78,43,85])
s2 = pd.Series(arr2)
s1
s2

0    11
1    34
2    78
3    43
4    85
dtype: int64

In [58]:
s1+s2

0     33
1     78
2    133
3    120
4    173
dtype: int64

## Comparison operator

In [59]:
s1>s2

0     True
1     True
2    False
3     True
4     True
dtype: bool

In [60]:
s1>=s2

0     True
1     True
2    False
3     True
4     True
dtype: bool

In [61]:
s1 == s2

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [62]:
s1 < s2

0    False
1    False
2     True
3    False
4    False
dtype: bool

In [63]:
s1 <= s2

0    False
1    False
2     True
3    False
4    False
dtype: bool

In [64]:
s.between(10,40)

0     True
1     True
2     True
3    False
4     True
5     True
dtype: bool

In [65]:
s1.equals(s2)

False

In [66]:
s1.compare(s2)

   self  other
0    22     11
1    44     34
2    55     78
3    77     43
4    88     85

In [67]:
arr1 = np.array([1,2,3,5,7])
s1 = pd.Series(arr1)
arr2 = np.array([1,2,4,5,6])
s2 = pd.Series(arr2)

In [68]:
s1.compare(s2)

   self  other
2   3.0    4.0
4   7.0    6.0

## Floating series with graph

In [85]:
import pandas as pd
s = pd.Series([40,20,30,40,50])
print(s.head(2))
print(s.tail(1))
print(s.sum())
print(s.count())
print(s.unique())
print(s.sort_values())
print(s.sort_index())
print(s.describe())
print(s.astype(float))
print(s.isnull)
print(s.sample())

0    40
1    20
dtype: int64
4    50
dtype: int64
180
5
[40 20 30 50]
1    20
2    30
0    40
3    40
4    50
dtype: int64
0    40
1    20
2    30
3    40
4    50
dtype: int64
count     5.000000
mean     36.000000
std      11.401754
min      20.000000
25%      30.000000
50%      40.000000
75%      40.000000
max      50.000000
dtype: float64
0    40.0
1    20.0
2    30.0
3    40.0
4    50.0
dtype: float64
<bound method Series.isnull of 0    40
1    20
2    30
3    40
4    50
dtype: int64>
4    50
dtype: int64