In [1]:
import numpy as np
import pandas as pd

In [7]:
data = pd.read_excel(r"C:\Users\Muskan Parmar\Downloads\pandas 4000 data.xlsx")
df = pd.DataFrame(data)
df

,Person ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,1,CA-2012-124891,2012-07-31,2012-07-31,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,...,TEC-AC-10003033,Technology,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...,2309.650,7,0.0,762.1845,933.57,Critical
1,1,IN-2013-77878,2013-02-05,2013-02-07,Second Class,JR-16210,Justin Ritter,Corporate,Wollongong,New South Wales,...,FUR-CH-10003950,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,-288.7650,923.63,Critical
2,11,IN-2013-71249,2013-10-17,2013-10-18,First Class,CR-12730,Craig Reiter,Consumer,Brisbane,Queensland,...,TEC-PH-10004664,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,919.9710,915.49,Medium
3,6,ES-2013-1579342,2013-01-28,2013-01-30,First Class,KM-16375,Katherine Murray,Home Office,Berlin,Berlin,...,TEC-PH-10004583,Technology,Phones,"Motorola Smart Phone, Cordless",2892.510,5,0.1,-96.5400,910.16,Medium
4,6,SG-2013-4320,2013-11-05,2013-11-06,Same Day,RH-9495,Rick Hansen,Consumer,Dakar,Dakar,...,TEC-SHA-10000501,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.960,8,0.0,311.5200,903.04,Critical
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
658,10,ES-2012-4934238,2012-02-02,2012-02-05,First Class,JH-15820,John Huston,Consumer,Hamburg,Hamburg,...,TEC-PH-10004910,Technology,Phones,"Samsung Signal Booster, Full Size",965.160,7,0.0,463.2600,253.09,High
659,10,IT-2013-5930911,2013-03-19,2013-03-19,Same Day,MV-17485,Mark Van Huff,Consumer,Saint-Chamond,Rhône-Alpes,...,OFF-ST-10000288,Office Supplies,Storage,"Fellowes Lockers, Industrial",748.116,4,0.1,282.5160,253.03,Critical
660,6,ES-2012-2674466,2012-03-21,2012-03-23,Second Class,JW-15955,Joni Wasserman,Consumer,Fontenay-aux-Roses,Ile-de-France,...,FUR-BO-10004844,Furniture,Bookcases,"Sauder Corner Shelving, Mobile",943.866,7,0.1,209.7060,252.90,Critical
661,12,IN-2014-54708,2014-05-24,2014-05-29,Second Class,LA-16780,Laura Armstrong,Corporate,Baotou,Inner Mongolia,...,FUR-BO-10001822,Furniture,Bookcases,"Dania Library with Doors, Metal",1447.440,4,0.0,43.3200,252.36,Medium
662,10,ES-2013-5085939,2013-06-14,2013-06-16,First Class,FM-14215,Filia McAdams,Corporate,Prato,Tuscany,...,TEC-AC-10003265,Technology,Accessories,"Belkin Router, Bluetooth",1552.500,6,0.0,62.1000,252.17,Medium

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 663 entries, 0 to 662
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Person ID       663 non-null    int64
 1   Order ID        663 non-null    str
 2   Order Date      663 non-null    datetime64[us]
 3   Ship Date       663 non-null    datetime64[us]
 4   Ship Mode       663 non-null    str
 5   Customer ID     663 non-null    str
 6   Customer Name   663 non-null    str
 7   Segment         663 non-null    str
 8   City            663 non-null    str
 9   State           663 non-null    str
 10  Country         663 non-null    str
 11  Postal Code     130 non-null    float64
 12  Market          663 non-null    str
 13  Region          663 non-null    str
 14  Product ID      663 non-null    str
 15  Category        663 non-null    str
 16  Sub-Category    663 non-null    str
 17  Product Name    663 non-null    str
 18  Sales           663 non-null    float64
 19  Quantity        663 non-null    int64
 20  Discount        663 non-null    float64
 21  Profit          663 non-null    float64
 22  Shipping Cost   663 non-null    float64
 23  Order Priority  663 non-null    str
dtypes: datetime64[us](2), float64(5), int64(2), str(15)
memory usage: 124.4 KB

In [12]:
df.head()           # Display the first 5 rows of the DataFrame
df.tail(10)

,Person ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
653,12,IN-2013-73608,2013-11-04,2013-11-08,Second Class,MF-17665,Maureen Fritzler,Corporate,Chaoyang,Jilin,...,TEC-MA-10002148,Technology,Machines,"Epson Printer, Durable",1839.180,7,0.000,238.9800,253.500,High
654,9,CA-2013-129630,2013-09-05,2013-09-05,Same Day,IM-15055,Ionia McGrath,Consumer,San Francisco,California,...,TEC-CO-10003763,Technology,Copiers,Canon PC1060 Personal Laser Copier,2799.960,5,0.200,944.9865,253.330,High
655,8,ES-2013-1776729,2013-11-19,2013-11-24,Standard Class,EB-13930,Eric Barreto,Consumer,Rugby,England,...,TEC-PH-10004823,Technology,Phones,"Nokia Smart Phone, Full Size",1908.180,3,0.000,820.4400,253.260,High
656,9,MX-2014-116267,2014-12-31,2015-01-03,Second Class,EB-13975,Erica Bern,Corporate,São Paulo,São Paulo,...,TEC-CO-10000137,Technology,Copiers,"Canon Wireless Fax, Color",1264.466,5,0.002,301.4660,253.254,High
657,6,CA-2013-103982,2013-03-04,2013-03-09,Standard Class,AA-10315,Alex Avila,Consumer,Round Rock,Texas,...,OFF-SU-10000151,Office Supplies,Supplies,High Speed Automatic Electric Letter Opener,3930.072,3,0.200,-786.0144,253.200,Medium
658,10,ES-2012-4934238,2012-02-02,2012-02-05,First Class,JH-15820,John Huston,Consumer,Hamburg,Hamburg,...,TEC-PH-10004910,Technology,Phones,"Samsung Signal Booster, Full Size",965.160,7,0.000,463.2600,253.090,High
659,10,IT-2013-5930911,2013-03-19,2013-03-19,Same Day,MV-17485,Mark Van Huff,Consumer,Saint-Chamond,Rhône-Alpes,...,OFF-ST-10000288,Office Supplies,Storage,"Fellowes Lockers, Industrial",748.116,4,0.100,282.5160,253.030,Critical
660,6,ES-2012-2674466,2012-03-21,2012-03-23,Second Class,JW-15955,Joni Wasserman,Consumer,Fontenay-aux-Roses,Ile-de-France,...,FUR-BO-10004844,Furniture,Bookcases,"Sauder Corner Shelving, Mobile",943.866,7,0.100,209.7060,252.900,Critical
661,12,IN-2014-54708,2014-05-24,2014-05-29,Second Class,LA-16780,Laura Armstrong,Corporate,Baotou,Inner Mongolia,...,FUR-BO-10001822,Furniture,Bookcases,"Dania Library with Doors, Metal",1447.440,4,0.000,43.3200,252.360,Medium
662,10,ES-2013-5085939,2013-06-14,2013-06-16,First Class,FM-14215,Filia McAdams,Corporate,Prato,Tuscany,...,TEC-AC-10003265,Technology,Accessories,"Belkin Router, Bluetooth",1552.500,6,0.000,62.1000,252.170,Medium

In [15]:
task = {
    'Id' : [1,2,3,4],
    'Dept' : ['IT','HR','IT', 'Ds'],
    'City' : ['Bhopal','Indore','Bhopal','Ujjain'],
    'Salary' : [10000,20000,30000,40000]
}
task
df = pd.DataFrame(task)
df

df.to_excel("muskan.xlsx")

In [19]:
data.to_csv("muskan.csv")
data

,Person ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,1,CA-2012-124891,2012-07-31,2012-07-31,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,...,TEC-AC-10003033,Technology,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...,2309.650,7,0.0,762.1845,933.57,Critical
1,1,IN-2013-77878,2013-02-05,2013-02-07,Second Class,JR-16210,Justin Ritter,Corporate,Wollongong,New South Wales,...,FUR-CH-10003950,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,-288.7650,923.63,Critical
2,11,IN-2013-71249,2013-10-17,2013-10-18,First Class,CR-12730,Craig Reiter,Consumer,Brisbane,Queensland,...,TEC-PH-10004664,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,919.9710,915.49,Medium
3,6,ES-2013-1579342,2013-01-28,2013-01-30,First Class,KM-16375,Katherine Murray,Home Office,Berlin,Berlin,...,TEC-PH-10004583,Technology,Phones,"Motorola Smart Phone, Cordless",2892.510,5,0.1,-96.5400,910.16,Medium
4,6,SG-2013-4320,2013-11-05,2013-11-06,Same Day,RH-9495,Rick Hansen,Consumer,Dakar,Dakar,...,TEC-SHA-10000501,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.960,8,0.0,311.5200,903.04,Critical
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
658,10,ES-2012-4934238,2012-02-02,2012-02-05,First Class,JH-15820,John Huston,Consumer,Hamburg,Hamburg,...,TEC-PH-10004910,Technology,Phones,"Samsung Signal Booster, Full Size",965.160,7,0.0,463.2600,253.09,High
659,10,IT-2013-5930911,2013-03-19,2013-03-19,Same Day,MV-17485,Mark Van Huff,Consumer,Saint-Chamond,Rhône-Alpes,...,OFF-ST-10000288,Office Supplies,Storage,"Fellowes Lockers, Industrial",748.116,4,0.1,282.5160,253.03,Critical
660,6,ES-2012-2674466,2012-03-21,2012-03-23,Second Class,JW-15955,Joni Wasserman,Consumer,Fontenay-aux-Roses,Ile-de-France,...,FUR-BO-10004844,Furniture,Bookcases,"Sauder Corner Shelving, Mobile",943.866,7,0.1,209.7060,252.90,Critical
661,12,IN-2014-54708,2014-05-24,2014-05-29,Second Class,LA-16780,Laura Armstrong,Corporate,Baotou,Inner Mongolia,...,FUR-BO-10001822,Furniture,Bookcases,"Dania Library with Doors, Metal",1447.440,4,0.0,43.3200,252.36,Medium
662,10,ES-2013-5085939,2013-06-14,2013-06-16,First Class,FM-14215,Filia McAdams,Corporate,Prato,Tuscany,...,TEC-AC-10003265,Technology,Accessories,"Belkin Router, Bluetooth",1552.500,6,0.0,62.1000,252.17,Medium