In [10]:
import numpy as np
import pandas as pd

In [11]:
data = pd.read_excel(r"C:\Users\Muskan Parmar\Downloads\Data to 1pm.xlsx")
df = pd.DataFrame(data)
print(df)

   Unnamed: 0  ID     Name   Age  Marks   Salary Department        Date
0           0   1    Alice  25.0   85.0  50000.0         HR  2026-01-15
1           1   2      Bob   NaN   90.0  60000.0    Finance  2026-02-10
2           2   3  Charlie  30.0    NaN      NaN         IT  2026-03-05
3           3   4    David  22.0   70.0  45000.0         IT  2026-04-12
4           4   4    David  22.0   70.0  45000.0         IT  2026-04-12
5           5   5      NaN  28.0   88.0  52000.0    Finance  2026-05-20
6           6   6      Eva   NaN   92.0  58000.0         HR  2026-06-18
7           7   7    Frank  35.0    NaN  61000.0    Finance  2026-07-25
8           8   8    Grace  29.0   76.0      NaN         IT  2026-08-30
9           9   9    Helen   NaN   80.0  55000.0         HR  2026-09-14

In [12]:
df.isna().sum().sum()

np.int64(8)

In [14]:
df.dropna()                   # remove null values
df.dropna(inplace= True) 
df

   Unnamed: 0  ID   Name   Age  Marks   Salary Department        Date
0           0   1  Alice  25.0   85.0  50000.0         HR  2026-01-15
3           3   4  David  22.0   70.0  45000.0         IT  2026-04-12
4           4   4  David  22.0   70.0  45000.0         IT  2026-04-12

In [ ]:
df.fillna(0 , inplace=True)    # fill the null vlaues

   Unnamed: 0  ID   Name   Age  Marks   Salary Department        Date
0           0   1  Alice  25.0   85.0  50000.0         HR  2026-01-15
3           3   4  David  22.0   70.0  45000.0         IT  2026-04-12
4           4   4  David  22.0   70.0  45000.0         IT  2026-04-12