In [1]:
import numpy as np
import pandas as pd

In [7]:
data = pd.read_excel(r"C:\Users\Muskan Parmar\Downloads\Data to 1pm.xlsx")
df = pd.DataFrame(data)
print(df)

   Unnamed: 0  ID     Name   Age  Marks   Salary Department        Date
0           0   1    Alice  25.0   85.0  50000.0         HR  2026-01-15
1           1   2      Bob   NaN   90.0  60000.0    Finance  2026-02-10
2           2   3  Charlie  30.0    NaN      NaN         IT  2026-03-05
3           3   4    David  22.0   70.0  45000.0         IT  2026-04-12
4           4   4    David  22.0   70.0  45000.0         IT  2026-04-12
5           5   5      NaN  28.0   88.0  52000.0    Finance  2026-05-20
6           6   6      Eva   NaN   92.0  58000.0         HR  2026-06-18
7           7   7    Frank  35.0    NaN  61000.0    Finance  2026-07-25
8           8   8    Grace  29.0   76.0      NaN         IT  2026-08-30
9           9   9    Helen   NaN   80.0  55000.0         HR  2026-09-14

In [3]:
#df.isna().sum().sum()

In [4]:
#df.dropna()                   # remove null values
#df.dropna(inplace= True) 
df

   Unnamed: 0  ID     Name   Age  Marks   Salary Department        Date
0           0   1    Alice  25.0   85.0  50000.0         HR  2026-01-15
1           1   2      Bob   NaN   90.0  60000.0    Finance  2026-02-10
2           2   3  Charlie  30.0    NaN      NaN         IT  2026-03-05
3           3   4    David  22.0   70.0  45000.0         IT  2026-04-12
4           4   4    David  22.0   70.0  45000.0         IT  2026-04-12
5           5   5      NaN  28.0   88.0  52000.0    Finance  2026-05-20
6           6   6      Eva   NaN   92.0  58000.0         HR  2026-06-18
7           7   7    Frank  35.0    NaN  61000.0    Finance  2026-07-25
8           8   8    Grace  29.0   76.0      NaN         IT  2026-08-30
9           9   9    Helen   NaN   80.0  55000.0         HR  2026-09-14

In [5]:
df.fillna(0 ,inplace=True)    # fill the null vlaues

TypeError: Invalid value '0' for dtype 'str'. Value should be a string or missing value, got 'int' instead.

In [ ]:
df["Marks"] = df["Marks"].fillna(0)
df

   Unnamed: 0  ID     Name   Age  Marks   Salary Department        Date
0           0   1    Alice  25.0   85.0  50000.0         HR  2026-01-15
1           1   2      Bob   NaN   90.0  60000.0    Finance  2026-02-10
2           2   3  Charlie  30.0    0.0      NaN         IT  2026-03-05
3           3   4    David  22.0   70.0  45000.0         IT  2026-04-12
4           4   4    David  22.0   70.0  45000.0         IT  2026-04-12
5           5   5      NaN  28.0   88.0  52000.0    Finance  2026-05-20
6           6   6      Eva   NaN   92.0  58000.0         HR  2026-06-18
7           7   7    Frank  35.0    0.0  61000.0    Finance  2026-07-25
8           8   8    Grace  29.0   76.0      NaN         IT  2026-08-30
9           9   9    Helen   NaN   80.0  55000.0         HR  2026-09-14

   Unnamed: 0  ID     Name   Age  Marks   Salary Department        Date
0           0   1    Alice  25.0   85.0  50000.0         HR  2026-01-15
1           1   2      Bob   NaN   90.0  60000.0    Finance  2026-02-10
2           2   3  Charlie  30.0    0.0      NaN         IT  2026-03-05
3           3   4    David  22.0   70.0  45000.0         IT  2026-04-12
4           4   4    David  22.0   70.0  45000.0         IT  2026-04-12
5           5   5      NaN  28.0   88.0  52000.0    Finance  2026-05-20
6           6   6      Eva   NaN   92.0  58000.0         HR  2026-06-18
7           7   7    Frank  35.0    0.0  61000.0    Finance  2026-07-25
8           8   8    Grace  29.0   76.0      NaN         IT  2026-08-30
9           9   9    Helen   NaN   80.0  55000.0         HR  2026-09-14

In [ ]:
df["Name"] = df["Name"].fillna("muskan")
df

   ID     Name   Age  Marks   Salary Department        Date
0   1    Alice  25.0   85.0  50000.0         HR  2026-01-15
1   2      Bob   NaN   90.0  60000.0    Finance  2026-02-10
2   3  Charlie  30.0    NaN      NaN         IT  2026-03-05
3   4    David  22.0   70.0  45000.0         IT  2026-04-12
4   4    David  22.0   70.0  45000.0         IT  2026-04-12
5   5   muskan  28.0   88.0  52000.0    Finance  2026-05-20
6   6      Eva   NaN   92.0  58000.0         HR  2026-06-18
7   7    Frank  35.0    NaN  61000.0    Finance  2026-07-25
8   8    Grace  29.0   76.0      NaN         IT  2026-08-30
9   9    Helen   NaN   80.0  55000.0         HR  2026-09-14

In [ ]:
df.drop(columns= "Unnamed: 0")               # remove column from dataset
df

KeyError: "['Unnamed: 0'] not found in axis"

In [ ]:
df.drop(columns = "Unnamed: 0", inplace= True)
df

   ID     Name   Age  Marks   Salary Department        Date
0   1    Alice  25.0   85.0  50000.0         HR  2026-01-15
1   2      Bob   NaN   90.0  60000.0    Finance  2026-02-10
2   3  Charlie  30.0    NaN      NaN         IT  2026-03-05
3   4    David  22.0   70.0  45000.0         IT  2026-04-12
4   4    David  22.0   70.0  45000.0         IT  2026-04-12
5   5      NaN  28.0   88.0  52000.0    Finance  2026-05-20
6   6      Eva   NaN   92.0  58000.0         HR  2026-06-18
7   7    Frank  35.0    NaN  61000.0    Finance  2026-07-25
8   8    Grace  29.0   76.0      NaN         IT  2026-08-30
9   9    Helen   NaN   80.0  55000.0         HR  2026-09-14

In [8]:
df.drop(columns = ["ID","Name", "Age"])

   Unnamed: 0  Marks   Salary Department        Date
0           0   85.0  50000.0         HR  2026-01-15
1           1   90.0  60000.0    Finance  2026-02-10
2           2    NaN      NaN         IT  2026-03-05
3           3   70.0  45000.0         IT  2026-04-12
4           4   70.0  45000.0         IT  2026-04-12
5           5   88.0  52000.0    Finance  2026-05-20
6           6   92.0  58000.0         HR  2026-06-18
7           7    NaN  61000.0    Finance  2026-07-25
8           8   76.0      NaN         IT  2026-08-30
9           9   80.0  55000.0         HR  2026-09-14

In [13]:
df.rename(columns= {"Age" : "idss"},inplace= True)

df

   Unnamed: 0  ID     Name  idss  Marks   Salary Department        Date
0           0   1    Alice  25.0   85.0  50000.0         HR  2026-01-15
1           1   2      Bob   NaN   90.0  60000.0    Finance  2026-02-10
2           2   3  Charlie  30.0    NaN      NaN         IT  2026-03-05
3           3   4    David  22.0   70.0  45000.0         IT  2026-04-12
4           4   4    David  22.0   70.0  45000.0         IT  2026-04-12
5           5   5      NaN  28.0   88.0  52000.0    Finance  2026-05-20
6           6   6      Eva   NaN   92.0  58000.0         HR  2026-06-18
7           7   7    Frank  35.0    NaN  61000.0    Finance  2026-07-25
8           8   8    Grace  29.0   76.0      NaN         IT  2026-08-30
9           9   9    Helen   NaN   80.0  55000.0         HR  2026-09-14

In [17]:
df.rename(columns= {"Marks" : "number", "Salary" : "Money"},inplace= True)

df

   Unnamed: 0  ID     Name  idss  number    Money Department        Date
0           0   1    Alice  25.0    85.0  50000.0         HR  2026-01-15
1           1   2      Bob   NaN    90.0  60000.0    Finance  2026-02-10
2           2   3  Charlie  30.0     NaN      NaN         IT  2026-03-05
3           3   4    David  22.0    70.0  45000.0         IT  2026-04-12
4           4   4    David  22.0    70.0  45000.0         IT  2026-04-12
5           5   5      NaN  28.0    88.0  52000.0    Finance  2026-05-20
6           6   6      Eva   NaN    92.0  58000.0         HR  2026-06-18
7           7   7    Frank  35.0     NaN  61000.0    Finance  2026-07-25
8           8   8    Grace  29.0    76.0      NaN         IT  2026-08-30
9           9   9    Helen   NaN    80.0  55000.0         HR  2026-09-14

In [20]:
df["ID"] = df["ID"].astype(float)
df

   Unnamed: 0   ID     Name  idss  number    Money Department        Date
0           0  1.0    Alice  25.0    85.0  50000.0         HR  2026-01-15
1           1  2.0      Bob   NaN    90.0  60000.0    Finance  2026-02-10
2           2  3.0  Charlie  30.0     NaN      NaN         IT  2026-03-05
3           3  4.0    David  22.0    70.0  45000.0         IT  2026-04-12
4           4  4.0    David  22.0    70.0  45000.0         IT  2026-04-12
5           5  5.0      NaN  28.0    88.0  52000.0    Finance  2026-05-20
6           6  6.0      Eva   NaN    92.0  58000.0         HR  2026-06-18
7           7  7.0    Frank  35.0     NaN  61000.0    Finance  2026-07-25
8           8  8.0    Grace  29.0    76.0      NaN         IT  2026-08-30
9           9  9.0    Helen   NaN    80.0  55000.0         HR  2026-09-14