In [3]:
import pandas as pd

In [5]:
data = pd.read_excel(r"C:\Users\Muskan Parmar\Downloads\group_by_data.xlsx")
df = pd.DataFrame(data)
print(df)

   Region Product  Sales  Quantity Month
0    East  Laptop   1200         2   Jan
1    East  Tablet    800         5   Jan
2    West  Laptop   1500         3   Jan
3    West  Tablet    600         4   Jan
4   North  Laptop   1000         2   Feb
5   North  Tablet    700         3   Feb
6   South  Laptop   1300         2   Feb
7   South  Tablet    900         4   Feb
8    East  Laptop   1400         3   Mar
9    East  Tablet    750         2   Mar
10   West  Laptop   1600         4   Mar
11   West  Tablet    850         5   Mar
12  North  Laptop   1100         2   Mar
13  North  Tablet    950         3   Mar
14  South  Laptop   1250         2   Mar
15  South  Tablet    650         2   Mar

In [6]:
gr = df.groupby("Region")
print(gr)

<pandas.api.typing.DataFrameGroupBy object at 0x00000225AEDC6F90>

In [7]:
for i, j in gr:
    print()
    display(i,j)

'East'

  Region Product  Sales  Quantity Month
0   East  Laptop   1200         2   Jan
1   East  Tablet    800         5   Jan
8   East  Laptop   1400         3   Mar
9   East  Tablet    750         2   Mar

'North'

   Region Product  Sales  Quantity Month
4   North  Laptop   1000         2   Feb
5   North  Tablet    700         3   Feb
12  North  Laptop   1100         2   Mar
13  North  Tablet    950         3   Mar

'South'

   Region Product  Sales  Quantity Month
6   South  Laptop   1300         2   Feb
7   South  Tablet    900         4   Feb
14  South  Laptop   1250         2   Mar
15  South  Tablet    650         2   Mar

'West'

   Region Product  Sales  Quantity Month
2    West  Laptop   1500         3   Jan
3    West  Tablet    600         4   Jan
10   West  Laptop   1600         4   Mar
11   West  Tablet    850         5   Mar