In [1]:
import pandas as pd

In [9]:
data = pd.read_excel(r"C:\Users\Muskan Parmar\Downloads\group_by_data.xlsx")
df = pd.DataFrame(data)
print(df)

   Region Product  Sales  Quantity Month
0    East  Laptop   1200         2   Jan
1    East  Tablet    800         5   Jan
2    West  Laptop   1500         3   Jan
3    West  Tablet    600         4   Jan
4   North  Laptop   1000         2   Feb
5   North  Tablet    700         3   Feb
6   South  Laptop   1300         2   Feb
7   South  Tablet    900         4   Feb
8    East  Laptop   1400         3   Mar
9    East  Tablet    750         2   Mar
10   West  Laptop   1600         4   Mar
11   West  Tablet    850         5   Mar
12  North  Laptop   1100         2   Mar
13  North  Tablet    950         3   Mar
14  South  Laptop   1250         2   Mar
15  South  Tablet    650         2   Mar

In [3]:
gr = df.groupby("Region")
print(gr)

<pandas.api.typing.DataFrameGroupBy object at 0x000001910E4F5940>

In [4]:
for i, j in gr:
    print()
    display(i,j)

'East'

  Region Product  Sales  Quantity Month
0   East  Laptop   1200         2   Jan
1   East  Tablet    800         5   Jan
8   East  Laptop   1400         3   Mar
9   East  Tablet    750         2   Mar

'North'

   Region Product  Sales  Quantity Month
4   North  Laptop   1000         2   Feb
5   North  Tablet    700         3   Feb
12  North  Laptop   1100         2   Mar
13  North  Tablet    950         3   Mar

'South'

   Region Product  Sales  Quantity Month
6   South  Laptop   1300         2   Feb
7   South  Tablet    900         4   Feb
14  South  Laptop   1250         2   Mar
15  South  Tablet    650         2   Mar

'West'

   Region Product  Sales  Quantity Month
2    West  Laptop   1500         3   Jan
3    West  Tablet    600         4   Jan
10   West  Laptop   1600         4   Mar
11   West  Tablet    850         5   Mar

In [5]:
gr = df.groupby("Product")
print(gr)

<pandas.api.typing.DataFrameGroupBy object at 0x000001910E8FAFD0>

In [6]:
for i, j in gr:
    print()
    display(i,j)

'Laptop'

   Region Product  Sales  Quantity Month
0    East  Laptop   1200         2   Jan
2    West  Laptop   1500         3   Jan
4   North  Laptop   1000         2   Feb
6   South  Laptop   1300         2   Feb
8    East  Laptop   1400         3   Mar
10   West  Laptop   1600         4   Mar
12  North  Laptop   1100         2   Mar
14  South  Laptop   1250         2   Mar

'Tablet'

   Region Product  Sales  Quantity Month
1    East  Tablet    800         5   Jan
3    West  Tablet    600         4   Jan
5   North  Tablet    700         3   Feb
7   South  Tablet    900         4   Feb
9    East  Tablet    750         2   Mar
11   West  Tablet    850         5   Mar
13  North  Tablet    950         3   Mar
15  South  Tablet    650         2   Mar

In [7]:
df.groupby("Month")["Sales"].agg("max")

Month
Feb    1300
Jan    1500
Mar    1600
Name: Sales, dtype: int64

In [8]:
df.groupby("Product")["Sales"].agg({"sum","mean"})

           sum     mean
Product
Laptop   10350  1293.75
Tablet    6200   775.00

In [ ]:
df["Remark"] = df["Sales"].apply(lambda a: "High" if a  )

In [10]:
df["Region"].value_counts()

Region
East     4
West     4
North    4
South    4
Name: count, dtype: int64

In [11]:
df["Quantity"].value_counts()

Quantity
2    7
3    4
4    3
5    2
Name: count, dtype: int64