In [13]:
import pandas as pd
import numpy as np

In [14]:
data = pd.read_excel(r"C:\Users\Muskan Parmar\Downloads\date data.xlsx")
df = pd.DataFrame(data)
print(df)

   S no     Name       Date
0     1   Tushar 2026-10-14
1     2   Pranav 2026-10-15
2     3   Tushar 2026-10-16
3     4   Pranav 2026-10-17
4     5  Sahitya 2026-10-18
5     6  Sahitya 2026-10-19
6     7  Sahitya 2026-10-20
7     8   Pranav 2026-10-21
8     9   Pranav 2026-10-22

In [15]:
df['year'] = df['Date'].dt.year
df

   S no     Name       Date  year
0     1   Tushar 2026-10-14  2026
1     2   Pranav 2026-10-15  2026
2     3   Tushar 2026-10-16  2026
3     4   Pranav 2026-10-17  2026
4     5  Sahitya 2026-10-18  2026
5     6  Sahitya 2026-10-19  2026
6     7  Sahitya 2026-10-20  2026
7     8   Pranav 2026-10-21  2026
8     9   Pranav 2026-10-22  2026

In [16]:
df['month'] = df['Days'].dt.year
df

KeyError: 'Days'

In [ ]:
df["months Name"] = df["Date"].dt.month_name()
df

   S no     Name       Date  year months Name
0     1   Tushar 2026-10-14  2026     October
1     2   Pranav 2026-10-15  2026     October
2     3   Tushar 2026-10-16  2026     October
3     4   Pranav 2026-10-17  2026     October
4     5  Sahitya 2026-10-18  2026     October
5     6  Sahitya 2026-10-19  2026     October
6     7  Sahitya 2026-10-20  2026     October
7     8   Pranav 2026-10-21  2026     October
8     9   Pranav 2026-10-22  2026     October

In [ ]:
df["Name"] = df['Name'].replace("Tushar", "Muskan")
df

   S no     Name       Date  year months Name
0     1   Muskan 2026-10-14  2026     October
1     2   Pranav 2026-10-15  2026     October
2     3   Muskan 2026-10-16  2026     October
3     4   Pranav 2026-10-17  2026     October
4     5  Sahitya 2026-10-18  2026     October
5     6  Sahitya 2026-10-19  2026     October
6     7  Sahitya 2026-10-20  2026     October
7     8   Pranav 2026-10-21  2026     October
8     9   Pranav 2026-10-22  2026     October

In [ ]:
# rename a single column and also try renaming more than one column in a single code
# try to change a data type of a column to another datatype 
# if my dataset has nan values than write a code to drop nan vlaues and also to replace nan value
# find the uninque
# find the duplic vlues of a specific col and write a code to find them and another code to drop them

In [17]:


data = {
    "Name": ["Aman", "Riya", "Rohan", "Aman", "Priya"],
    "Age": [21, 22, np.nan, 21, 24],
    "Marks": [85, 90, 78, 85, np.nan],
    "City": ["Indore", "Bhopal", "Indore", "Indore", "Delhi"]
}

df = pd.DataFrame(data)

print(df)

    Name   Age  Marks    City
0   Aman  21.0   85.0  Indore
1   Riya  22.0   90.0  Bhopal
2  Rohan   NaN   78.0  Indore
3   Aman  21.0   85.0  Indore
4  Priya  24.0    NaN   Delhi

In [18]:
df.rename(columns={"Name": "Student_Name"}, inplace=True)

print(df)

  Student_Name   Age  Marks    City
0         Aman  21.0   85.0  Indore
1         Riya  22.0   90.0  Bhopal
2        Rohan   NaN   78.0  Indore
3         Aman  21.0   85.0  Indore
4        Priya  24.0    NaN   Delhi

In [19]:
df.rename(columns={
    "Age": "Student_Age",
    "Marks": "Student_Marks",
    "City": "Student_City"
}, inplace=True)

print(df)

  Student_Name  Student_Age  Student_Marks Student_City
0         Aman         21.0           85.0       Indore
1         Riya         22.0           90.0       Bhopal
2        Rohan          NaN           78.0       Indore
3         Aman         21.0           85.0       Indore
4        Priya         24.0            NaN        Delhi

In [21]:
df["Student_Age"] = df["Student_Age"].astype("Int64")

print(df.dtypes)

df["Student_City"] = df["Student_City"].astype(str)
print(df.dtypes)

Student_Name         str
Student_Age        Int64
Student_Marks    float64
Student_City         str
dtype: object
Student_Name         str
Student_Age        Int64
Student_Marks    float64
Student_City         str
dtype: object

In [22]:
df["Student_Marks"] = df["Student_Marks"].fillna(0)

print(df)

  Student_Name  Student_Age  Student_Marks Student_City
0         Aman           21           85.0       Indore
1         Riya           22           90.0       Bhopal
2        Rohan         <NA>           78.0       Indore
3         Aman           21           85.0       Indore
4        Priya           24            0.0        Delhi

In [23]:
df["Student_Marks"] = df["Student_Marks"].fillna(
    df["Student_Marks"].mean()
)

In [ ]:
print(df["Student_City"].unique())

df.drop_duplicates(subset=["Student_Name"], inplace=True)

print(df)