In [9]:
import pandas as pd

In [10]:
data = pd.read_excel(r"C:\Users\Muskan Parmar\Downloads\date data.xlsx")
df = pd.DataFrame(data)
print(df)

   S no     Name       Date
0     1   Tushar 2026-10-14
1     2   Pranav 2026-10-15
2     3   Tushar 2026-10-16
3     4   Pranav 2026-10-17
4     5  Sahitya 2026-10-18
5     6  Sahitya 2026-10-19
6     7  Sahitya 2026-10-20
7     8   Pranav 2026-10-21
8     9   Pranav 2026-10-22

In [11]:
df['year'] = df['Date'].dt.year
df

   S no     Name       Date  year
0     1   Tushar 2026-10-14  2026
1     2   Pranav 2026-10-15  2026
2     3   Tushar 2026-10-16  2026
3     4   Pranav 2026-10-17  2026
4     5  Sahitya 2026-10-18  2026
5     6  Sahitya 2026-10-19  2026
6     7  Sahitya 2026-10-20  2026
7     8   Pranav 2026-10-21  2026
8     9   Pranav 2026-10-22  2026

In [12]:
df['month'] = df['Days'].dt.year
df

KeyError: 'Days'

In [14]:
df["months Name"] = df["Date"].dt.month_name()
df

   S no     Name       Date  year months Name
0     1   Tushar 2026-10-14  2026     October
1     2   Pranav 2026-10-15  2026     October
2     3   Tushar 2026-10-16  2026     October
3     4   Pranav 2026-10-17  2026     October
4     5  Sahitya 2026-10-18  2026     October
5     6  Sahitya 2026-10-19  2026     October
6     7  Sahitya 2026-10-20  2026     October
7     8   Pranav 2026-10-21  2026     October
8     9   Pranav 2026-10-22  2026     October